Move submission-review-ui to v5
topcoder-platform/submission-review-ui pull request #73
Opened 2023-08-10 13:19 UTC by marioskranitsas

2023-08-18 10:13 UTC, eisbilir requested changes

2023-08-24 11:33 UTC, marioskranitsas commented
Regarding the comment about the user handles/colors, we don't have this information on the v5 API response thus it was removed. The V4 API included the list of registrants with their rating which we no longer support. We can ignore this.

2023-08-24 12:23 UTC, eisbilir commented
> Regarding the comment about the user handles/colors, we don't have this information on the v5 API response thus it was removed. The V4 API included the list of registrants with their rating which we no longer support. We can ignore this.

So, we won't even show the member handle? https://github.com/topcoder-platform/submission-review-ui/blob/PLAT-3086/src/components/ChallengeDetailsComponent/List/SubmissionList/index.js#L52-L58

2023-08-24 12:24 UTC, eisbilir requested changes

2023-08-24 12:24 UTC, eisbilir commented on src/components/ChallengeDetailsComponent/ChallengeInfo/Phases/index.js
> +  const circle = (p) => <div className={cn(styles.circle, { [styles.green]: p.isOpen || !!p.actualEndDate })} />
{circle(p.isOpen)} should be updated to  {circle(p)}

2023-09-13 10:48 UTC, eisbilir approved these changes

2023-09-13 10:59 UTC, merged